#!/bin/bash

START_DATE=$1
AUTHOR_EMAIL=$(git config --get user.email)

git log --since="${START_DATE}" --all --oneline --no-merges --author-date-order --reverse --abbrev-commit --author ${AUTHOR_EMAIL}
